"""empty message

Revision ID: f857f2eb8b58
Revises: 918a329faf46
Create Date: 2023-06-20 19:55:29.662793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f857f2eb8b58'
down_revision = '918a329faf46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_types',
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    op.add_column('chunks', sa.Column('biome', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'chunks', 'chunk_types', ['biome'], ['type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'biome')
    op.drop_table('chunk_types')
    # ### end Alembic commands ###
